# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-03 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empID', models.IntegerField()),
                ('dept', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('workID', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=4)),
                ('birthday', models.DateField()),
            ],
        ),
    ]
